# Generated by Django 5.0.4 on 2024-05-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=120)),
                ('author_name', models.CharField(max_length=60)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
